### ISSUE TITLE
Horizontal lines when creating horizon mask

### ISSUE THREAD

**Issue by Jelgo1** [mworion/MountWizzard4#331] opened 2023-10-05 14:35 UTC
![image0 (1)](https://github.com/mworion/MountWizzard4/assets/147074691/5e1a17fb-6122-4cdf-9410-1339481a9504)
Hello!
Where am I going wrong when creating a horizon mask in MW4?  The 2 unwanted horizontal lines seem to prevent model build points being created below them, rather than using the horizon that I define. I don’t know how I am creating these 2 lines in error.
I create the horizon by pointing my scope at the horizon through 360 degrees, clicking on the button to create the horizon points as I go. I’ve tried deleting horizon points that I have made, but the 2 horizontal lines remain.
Thanks!

**Comment by mworion** [comment] 2023-10-06 17:44
Hi,
never seen this, could you post the horizon file you created? It should be under config in your work folder. In addition if possible the log file as well.
Many thanks,
Michel

**Comment by Jelgo1** [comment] 2023-10-06 19:08
Hi Michel,
I hope that you can see the two files attached. I am a novice so I may not
have sent exactly what you need. I am sure that the problem is user error!
Regards,
Jonathan

**Comment by mworion** [comment] 2023-10-07 11:51
Jonathan,
unfortunately not as you need to drop them on the web page. An attachment to the automatic mail will not be added in Github.
Michel

**Comment by Jelgo1** [comment] 2023-10-07 13:15
Second try at adding attachments...
Jonatyhan :)
[mw4-2023-09-12.zip](https://github.com/mworion/MountWizzard4/files/12837864/mw4-2023-09-12.zip)
[Home Horizon 3 April 2023.zip](https://github.com/mworion/MountWizzard4/files/12837868/Home.Horizon.3.April.2023.zip)

**Comment by mworion** [comment] 2023-10-07 16:42
Jonathan,
the problem is, that for whatever reason the horizon points are in reverse azimuth order. An there was no possibility to change that within MW4. This causes your situation.
I changed this by sorting when loading and after editing. The fix will be in v3.2.3 service release published later this evening. For you after upgrading to 3.2.3, there is nothing to do and it should work out of the box.
Michel

**Comment by Jelgo1** [comment] 2023-10-07 17:42
Thanks for looking into this and resolving it so quickly. MW4 is an  excellent app!
Jonathan :)

**Closed** 2023-10-07 18:19 UTC
Labels: bug, enhancement
