### ISSUE TITLE
Dome geometry trial

### ISSUE THREAD

**Issue by ACMBakx** [mworion/MountWizzard4#46] opened 2020-06-03 20:39 UTC
[mw4-2020-06-03.log](https://github.com/mworion/MountWizzard4/files/4726090/mw4-2020-06-03.log)

Just ran a small golden cirkel model east/west order.
Found dome settings that give good accuracy for dome alignment.
However found accidentally 2 area's where things go wrong.
Sky points at 59 deg alt and az 36 and az 324
Point #16 in the model and the mirrored one.
Here the dome is send in the opposite direction.
In this dome position the telescope is looking against the dome roof,
When I rotate the dome at the same az as the telescope, the telescope just looks under top edge of the slot.
Points at a small distance from these 2 points cause the dome to find an acceptable position.
See the log #point16 was the troublemaker.
All the other points were well aligned within limits.
The numbers are ofcourse only valid for my set-up dimensions.
Regards
Arie

**Comment by ACMBakx** [comment] 2020-06-03 20:44
If the dome slot would have been 20cm longer over the top, this position would be ok,
But my dome slot stops just passed zenith. But with the dome and scope az being the same in these 2 positions, the telescope peeks just under the edge.

**Comment by ACMBakx** [comment] 2020-06-04 15:51
Checked today against theScopedomedriver telescope sync option.
This connects with the the telescope via poth.
Here the dome is pointed in the correct direction.

**Comment by InFINNity-Deck** [comment] 2020-06-04 21:47
The way dome azimuth is calculated, is by calculating the intersection between the line-of-sight from the OTA through the spherical shape of the dome. These intersections are calculated in 3D relatively to the dome's centre. The required azimuth is calculated from the horizontal coordinates of the intersection. The reason why the dome makes a (seemingly unnecessary) large slew is caused by the location, relatively to the dome's centre, where the line-of-sight intersects the dome. When taking a steep sight in for instance direction west, it can well be that the intersection occurs just east of the dome's centre. As a result of this the dome is steered east, while the scope is aimed west. How often this depend of course depends on how high the mount sits within the dome, its horizontal offset to the dome's centre, and the size of the mount itself, including the GEM- and lateral-offsets.

On itself these large dome slews can be avoided if the length and width of the slit and diameter of the OTA are known. As long as the distance from the dome centre remains smaller than the length and width of the slit (corrected for half the OTA's diameter on all three sides) the dome needs not to slew. For lower altitudes, the same is true when the azimuth of the target is within the width of the slit (again minus half the OTA's diameter on both sides).

The main problem in addressing this, is the accuracy with which the dome is steered. In my case it has an accuracy of about 2 degrees, which equals to about 5cm at a radius of 1.5 metres (about one-third the diameter of my deep-sky imaging scope). So for determining whether or not the dome should slew, this amount should be taken into in account when comparing the current dome's azimuth to the newly calculated azimuth. So if the newly calculated azimuth is away from the dome's slit-edge by (half OTA diameter + dome slew accuracy) then no slew is required. The slit of my dome is 80cm wide and runs 40cm overhead, making this marging 7.5 + 5 = 12.5cm, leaving a useable space within the slit of 55cm (roughly 20 degrees for my dome).

Nicolàs

**Comment by mworion** [comment] 2020-06-13 12:43
Hopefully a tested dome geometry calculation will be in 0.150.25 release soon.

**Comment by ACMBakx** [comment] 2020-06-13 16:41
The last geometry test I ran was very accurate Michael.

**Comment by mworion** [comment] 2020-06-14 12:13
Arie,
thanks for the feedback. Closing this issue now with the release of 0.150.25

**Closed by mworion** 2020-06-14 12:13 UTC

**Comment by InFINNity-Deck** [comment] 2020-06-14 18:34
I confirm Arie's findings, indeed very accurate, thanks a bunch!

Nicolàs
