### ISSUE TITLE
Dome not following correctly when tracking satellites

### ISSUE THREAD

**Issue by InFINNity-Deck** [mworion/MountWizzard4#139] opened 2021-04-04 12:10 UTC
Hi Michel,

as discussed on the 10Micron forum recently, the new dome following function in satellite tracking does not work properly. At the time I only tested it for negative lateral offset of my C11, but today I tested it both for the C11 and the Esprit (positive lateral offset). Both scopes do not get the desired dome-slew.

I also tested a modelling run and that worked just fine with both lateral offsets, the dome was correctly positioned in both cases.

Any idea what could be causing this deviation in satellite tracking?

Thanks and best wishes,
Nicolàs

**Comment by mworion** [comment] 2021-04-04 14:48
Nicolas,
from my point the mount computer does not set the target pier side when doing satellite tracking. This might be the difference. I have to look, how I could make this happen.
Michel

**Comment by InFINNity-Deck** [comment] 2021-04-04 14:52
Hi Michel,

ok, that is interesting. Please let me know if I can test something for you.

Nicolàs

**Comment by mworion** [comment] 2021-04-05 16:39
Nicolas,
I uploaded v2.0.0b2 with an updated procedure for following. Hop this improves the situation.
Michel

**Comment by InFINNity-Deck** [comment] 2021-04-05 19:03
Hi Michel,

thanks for the quick update, much appreciated! Currently the weather has taken a turn for the worst (7Bft, snow!), hope to dry-test it tomorrow when the weather has calmed down again.

Nicolàs

**Comment by mworion** [comment] 2021-07-15 16:47
Hi Nicolas,
the actual weather is still very bad. I try to clean up open verifications as I want to move to release v2. Please let me know if there is anything new about the dome following.
Michel

**Comment by InFINNity-Deck** [comment] 2021-07-15 20:40
Hi Michel,

work, weather and seasonal daylight have prevented further tests. I will put this high on my agenda and will try to find time for a 'dry-test' (i.e. at daytime)

Nicolàs

**Comment by InFINNity-Deck** [comment] 2021-07-17 12:44
Hi Michel,

today I did three tests:

- OAO 2 using the C11 (offLat = -0.19)
- Cosmos 2221 using the C11 (offLat = -0.19)
- Cosmos 1833 using the Esprit 150ED (offLat = +0.21)

In all three cases the dome followed exactly as it should, so great result! :-)

I do, however, have a few comments:

- the initial slew seems to be random. With OAO 2 the initial dome position was about 100 degrees off, with Cosmos 2221 this was about -45 degrees. Switching to the Esprit set-up disabled the automatic dome following function, so I do not know the initial dome-slew for that test.
- Once the satellite is above the horizon the dome is slewed to its proper location and the slit stays properly centred in front of the selected scope.
- During tracking the amount of dome-slews is quite large. Every 3-5 seconds the dome is instructed to follow the scope. I have a dome-slit-width programmed in at 0.81 metres, but the routine does not seem to make use of that knowledge.

So the functionality works perfect, but could do with some improvement regarding the number of corrections for the slit-width. I do realise that it is not quite easy to do the required maths, but it would be great if dome slewing could be done as follows:

- start with the slit centred over the scope;
- once tracking, move the dome when about 10-20% near the slit's railing edge;
- then move the dome towards the leading edge (again some 10-20% clear of it);
- wait until the trailing edge is reached again.

As the satellite trajectories are curved in respect to the dome slit, the above steps require knowledge of the complete trajectory. Calculating the optimum slew-angle has to be done for several points along the trajectory to ensure the dome is not slewed too far off.

The reason I would appreciate the number of dome-slews to be minimised is that each dome slew has its effect on the pier (despite the vibrations going down one floor to reach the base of the pier), which is especially noticeable at f/40 with the C11.

Once again thanks for this improvement! Hopefully you are able to implement above suggestion viz. the reduction of slew commands as well.

Nicolàs

**Comment by mworion** [comment] 2021-07-17 13:06
Hi Nicolas,
thanks for the extended testing. It's good that it works now as it should. For the Dome movements (as I don't have one) I need some more context, how dome is functioning. Currently I send always if I correct the the Azimuth also a new dome position. There is right now no relation to the slit width. I recognized that some does controllers (like Aries one) have a configured hysteresis where it does not react at all (e.g. 2 deg). So any chance within this value, the dome does not move. I struggled with that as the dome Dows not reach the traget position (and I had the dome slewing state present). In addition if I take care of the slit with (which is doable), the hysteresis parts are summing up. Problem is that hysteresis settings are normally not readable from the dome controllers nor being able to switch them on or off. Plus as you already showed, depending of the position the resulting dome slit with is due to change if the scope is not located in the center line (which is always the case in side-by-side setups).

If you have some thoughts about how to address this, please let me know (especially how you as a dome user interact with these unlinked controls)
Michel

**Comment by mworion** [comment] 2021-07-18 07:29
Edit: I put the reducing dome slews into a new issue to separate this.
regarding your Radom initial dome position: Could you post the log file of the tests. I actually cannot reproduce this behavior in my simulation setup.
Thanks in advance,
Michel

**Comment by InFINNity-Deck** [comment] 2021-07-18 08:21
Hi Michel,

please find attached the log-file.
[mw4-2021-07-17.log](https://github.com/mworion/MountWizzard4/files/6835863/mw4-2021-07-17.log)

Nicolàs

**Comment by mworion** [comment] 2021-07-18 11:30
Nicolas,
checked the logs. Does your dome has an open shutter status in the ASCOM driver ? Still I have to be robust and made some fixes.
Anyway I made a new beta, which addressed this topic (v2.0.0b25).
Michel

**Comment by InFINNity-Deck** [comment] 2021-07-18 15:54
Hi Michel,

the shutters of my dome are not yet automated while the ASCOM driver I currently use has a bug by which it reports a wrong status. This issue has been dealt with, but I still need to update the LesveDome ASCOM driver.

Thanks for yet another update, will try to test it later this week.

Nicolàs

**Comment by mworion** [comment] 2021-07-22 19:03
Nicolas,
with the other test, did this workaround help?
Michel

**Comment by InFINNity-Deck** [comment] 2021-07-22 20:56
Dear Michel,

forgive me, but I am not sure if I understand well. Which workaround should help for which issue?

Nicolàs

**Comment by mworion** [comment] 2021-07-22 21:04
I put a workaround in for the dome driver not reporting the right status.

**Comment by InFINNity-Deck** [comment] 2021-07-22 21:06
Ah, ok, I did not notice that. Will have a look at it next time, but perhaps you see it in the logs I just sent?

Nicolàs

**Comment by InFINNity-Deck** [comment] 2021-07-22 21:18
I just checked which LesveDome driver I currently use and noticed that I am already using the latest one which should have the shutter status error fixed. In SGP, however, I still see "Shutter status: Error".

Nicolàs

**Comment by mworion** [comment] 2021-07-23 05:30
OK, but I should not hurt MW4 anymore.

**Comment by mworion** [comment] 2021-09-22 18:49
Nicolas, I close the issue, if anything newly happens, please reopen.
Michel

**Closed by mworion** 2021-09-22 18:49 UTC
Labels: in verification
