### ISSUE TITLE
ASTAP Solver Failed

### ISSUE THREAD

**Issue by jmhirschi** [mworion/MountWizzard4#57] opened 2020-06-28 20:26 UTC
Hello,

I try to solve my images with ASTAP from MW4 (v0.150.26)

![image](https://user-images.githubusercontent.com/55414966/85957481-f5960b80-b98d-11ea-836f-452ab2e1e5d8.png)

I receive immediately the following message

![image](https://user-images.githubusercontent.com/55414966/85957516-41e14b80-b98e-11ea-9d3d-5c6f4cf4cd48.png)

When I try to solve the same image directly from ASTAP the solving is perfect.

Best regards,

Jean-Michel

**Comment by mworion** [comment] 2020-06-29 18:11
Hi Jean-Michel,

Just tried it, with a test image it works. So please do me a favour: zip this fits file and drag it to the GitHub issue and drop the log file as well. That’s the best and easiest way to find out

Michel

**Comment by mworion** [comment] 2020-07-02 13:51
Any news?

**Comment by jmhirschi** [comment] 2020-07-02 20:07
Hello Michel,

First of all many thanks for your support and quick answer. I should apologize for my late answer. I've attached the requested files but in the meantime I've been able to solve the image having uninstalled and reinstalled ASTAP on a different drive (on the drive C: now). I don't know if the move from D: to C: was the solution but at least I'm now able to solve images with ASTAP from MW4.

I'm now facing another issue when I run a Model Build. Everything work well (points, slew, image acquisition) but the solve stay at 0 and the model is not updated

Please look at the log from the 2020-06-29.

Many thanks.







[mw4-2020-06-28.log](https://github.com/mworion/MountWizzard4/files/4866364/mw4-2020-06-28.log)
 
[mw4-2020-06-29.log](https://github.com/mworion/MountWizzard4/files/4866415/mw4-2020-06-29.log)

**Comment by mworion** [comment] 2020-07-03 18:26
Hi,

the log files saying that calling ASTAP needs elevation in rights. So you may have the situation that ASTAP is installed with admin rights (which should not be necessary) and afterwards MW4 tries to run it as normal user. 

Please check this.

Michel

**Comment by jmhirschi** [comment] 2020-07-05 20:43
Hi Michel,

I checked the installation parameters of the two software and neither Astrap nor MW4 have administrator rights.

Jean-Michel

**Comment by mworion** [comment] 2020-07-06 10:41
OK, understood,
did you disable UAC (User account control) ?
Michel

**Comment by jmhirschi** [comment] 2020-07-06 11:59
Hi Michel,

Thanky you so much for your active support. On my PC the UAC is **disabled**. See the screen shot below.

![image](https://user-images.githubusercontent.com/55414966/86590808-9c7f3680-bf90-11ea-8cbb-7c4dd05dfde5.png)

**Comment by mworion** [comment] 2020-07-06 12:55
OK, please let me know, where you now installed ASTAP exactly (Path). I will log that in future. I just log that everything is there, but not where. 
Michel

**Comment by jmhirschi** [comment] 2020-07-06 15:42
ASTAP is installed under 

C:\Program Files\astap

**Comment by mworion** [comment] 2020-07-07 09:41
Jean-Michel,
I can't reproduce your observations in my environment. Nor with different UAC settings nor with other tweaks. I will publish a test release with some extended logging to capture that.
Only point (from theory) left: 
Where is the star database located ?
And: please move the work dir from desktop to a user folder (e.g. new folder or documents) as windows10 tends to treat the desktop as a restricted area and might ask for elevation when writing a file, too.
Michel

**Comment by jmhirschi** [comment] 2020-07-07 21:32
Michel,

The star database is stored in the same folder as ASTAP.

I've moved the work folder under c:/Program Files/work and ran a small model build but still same issue. The model build ran perfectly, capture the images but doesn't solve them

![image](https://user-images.githubusercontent.com/55414966/86845178-67b2d280-c0a9-11ea-9751-7a86b7389403.png)
.  
Another strange thing is that I don't receive any information about the time but it's a detail.

When I manually load and solve the saved images created by the model build then ASTAP is able to solve (and this fromMW4).  

Cheers.

Jean-Michel

**Comment by Ruediger3** [comment] 2020-07-07 21:57
Hello both,
I had some similar issues the past few days. Solving did simply not work, No output in the log windows at all, Even restarting MW did not help. It turned out, there was always a stalled instance of ASTAP in the background, because ASTAP could not solve the very first image. Maybe this is a different case but it had the exact same symptoms.

**Comment by mworion** [comment] 2020-07-09 07:54
Rüdiger,
do you have a log for this event? Would be helpful.
Jean-Michel, could you comment on this ?
Michel

**Comment by Ruediger3** [comment] 2020-07-09 08:57
Hi Michel,
Yes I do have all the logs, but the problem is I cannot find the proper one, since I start MW every day and they are huge. I have attached the log of the day, where it likely happened, but I guess it is useless, since I cannot ensure it is the right one.

[mw4-2020-07-05.zip](https://github.com/mworion/MountWizzard4/files/4895594/mw4-2020-07-05.zip)
.

**Comment by jmhirschi** [comment] 2020-07-09 08:58
Hi Michel and Rüdiger,
I ran another test yesterday evening with no success. I do not detect any
instance of ASTAP running in the background like described by Rüdiger but
the final result is similar. No solving at all.

**Comment by mworion** [comment] 2020-07-15 16:46
@Ruediger3,
in the log, there is no problem with ASTAP. ASTAP solved within 0.9 - 1.2 sec.

@jmhirschi,
you said, you could solve the file through MW4 when loading it in image window and manual start solving. Right ?
The message about time is easy to explain: Their first update will be made after the first solve to estimate the overall process time. If you don't get a solve, no estimation possible -> not time display.

Michel

**Comment by mworion** [comment] 2020-07-15 17:58
No Problem and thanks for helping.

**Comment by jmhirschi** [comment] 2020-07-18 13:03
> @Ruediger3,
> in the log, there is no problem with ASTAP. ASTAP solved within 0.9 - 1.2 sec.
> 
> @jmhirschi,
> you said, you could solve the file through MW4 when loading it in image window and manual start solving. Right ?
> The message about time is easy to explain: Their first update will be made after the first solve to estimate the overall process time. If you don't get a solve, no estimation possible -> not time display.
> 
> And could you post a new log file from new asap installation ?
> 
> Michel

Hello Michel,

Correct, I can solve an image from MW4 without any problem.
[mw4-2020-07-08.log](https://github.com/mworion/MountWizzard4/files/4941669/mw4-2020-07-08.log)

**Comment by mworion** [comment] 2020-07-22 16:22
OK,

within the provided Log file there is no manual solve in it. An there is no model run in. Just that ASTAP is found and some interactions with satellite

Michel

**Comment by jmhirschi** [comment] 2020-08-11 14:55
Dear Michel,

I've entirely reinstalled MW4 on a NUC W10 PC and everything works well now. I know I'm no more in the same configuration as when I launched this request but today my initial issue is solved. Can we close this issue or you want to continue in order to solve the Ruediger's problem ?

**Comment by mworion** [comment] 2020-08-11 15:24
As Rüdiger is able to work without problems, you can close it. 
Michel

**Comment by Ruediger3** [comment] 2020-08-11 15:50
I am fine with that. Currently every thing works as expected. Maybe only a hick up.

**Closed** 2020-08-11 17:48 UTC
